# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76cb6719fb235c0c1edd2ea1462ceef1395c273f2177a7d12adac47a4cdf555d15a844158000931aeafb8e7b70449d9387cbb8549fe88aa16195c44abe7123e6

test:
  secret_key_base: 896a6d89bb7b4f61e88183f4e2f2c972aadc8b320dfb6dfd1a6f0d5555953cd89d7006256646f88a362d45a8e2fc9338f321de8e71ff013861569a5abaa173ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
